### ISSUE TITLE
Random event not hidden

### ISSUE THREAD

**Issue by pettrs** [YvesW/random-event-hider#2]
Sandwich lady is still showing up for me with the plugin enabled, not sure if this goes for other NPCs too, or if it's just crashing with another plugin

![image](https://user-images.githubusercontent.com/75093127/212780248-c0e63f9e-a33d-4d6d-a66e-cb4b50cf4642.png)

**Comment by YvesW** [comment]
That's because I made the code not work in instances before, since I thought random events did not spawn in instances. However, I'd forgotten that randoms spawn inside the POH! Thanks for letting me know, but I've already sneakily fixed it a couple days in 46cdfc953b086fdbeae9ed18d2d604876f7896e7
I'd like to add and test some new functionality before shipping it to the pluginhub however, so the new functionality and fixes can go in at the same time, so it'll take a couple days before I'll submit it!
