### ISSUE TITLE
'Hide others' Kiss the Frog' Hides Frogland frogs

### ISSUE THREAD

**Issue by mo-pi** [YvesW/random-event-hider#4]
If you dont kiss the princess for the frog random event she teleports you to "Frogland" where you need to talk with her again to leave. With the `Hide other' Kiss the frog` enabled all the npcs in "Frogland" will be invisible.

![image](https://github.com/YvesW/random-event-hider/assets/20108256/b3c590c9-a99b-4ebc-84dd-2664330e3034)

**Comment by YvesW** [comment]
So I assume this happens when you specifically talk to a frog princess and then decline? I thought they removed this area or used different npc ids there lol.
The issue does completely make sense then; they are apparently using the same ids as the overworld and are not interacting with you, so the plugin thinks these are others' random events.
Should be fixable by simply checking the region; I think it's 38,74 on mejrs

**Comment by YvesW** [comment]
Fixed in https://github.com/YvesW/random-event-hider/commit/187365c3a04c5a1c35a5238f5120de405c5a7ff8
